#!/bin/sh
echo '---------------- remove system vim & install depedents --------------------'
sudo rm ~/.vimrc
sudo rm ~/.viminfo
sudo mv ~/.vim ~/.vim.bak.`date +%y%m%d%H%M%S`
sudo apt-get remove vim vim-common vim-tiny 
sudo apt-get install libncurses5-dev libgnome2-dev libgnomeui-dev \
    libgtk2.0-dev libatk1.0-dev libbonoboui2-dev \
    libcairo2-dev libx11-dev libxpm-dev libxt-dev python-dev \
    python3-dev ruby-dev lua5.1 lua5.1-dev libperl-dev git \
    cmake g++

echo '------------------------- clone vim source --------------------------------'
cd ~/prog
git clone https://github.com/vim/vim.git
cd vim/src
./configure --with-features=huge \
            --enable-multibyte \
            --enable-rubyinterp=yes \
            --enable-pythoninterp=yes \
            --with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu \
            --enable-perlinterp=yes \
            --enable-luainterp=yes \
            --enable-gui=gtk2 --enable-cscope --prefix=/usr
echo ----'-------------------------- nake vim ----------------------------------'
make VIMRUNTIMEDIR=/usr/share/vim/vim80 -j8
echo '---------------------------- install vim ---------------------------------'
sudo make uninstall
sudo make install

#sudo update-alternatives --install /usr/bin/editor editor /usr/bin/vim 1
#sudo update-alternatives --set editor /usr/bin/vim
#sudo update-alternatives --install /usr/bin/vi vi /usr/bin/vim 1
#sudo update-alternatives --set vi /usr/bin/vim

echo '--------------------------- install Vundle -------------------------------'
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
wget https://raw.githubusercontent.com/houxd/vim/master/.vimrc -O ~/.vimrc

echo '-------------------------- install uncrustify ----------------------------'
rm /tmp/uncrustify -rf
git clone https://github.com/uncrustify/uncrustify /tmp/uncrustify
cd /tmp/uncrustify/
cmake ..
cmake --build .
sudo make install

echo '-------------------------- vim install plugin ----------------------------'
sudo vim -c ':PluginInstall'

#vim<<：PluginInstall
echo '------------------- install YouCompleteMe c++ surppot---------------------'
#download libclang
if uname -v|grep Ubuntu|grep 16.04; then
    wget http://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz -O /tmp/clang.tar.xz
else
    echo 'only test in ubuntu 16.04'
    exit
fi
mkdir ~/ycm_temp
cd ~/ycm_temp
tar jxvf /tmp/clang.tar.xz
mv `ls` llvm_root_dir
cd ~/ycm_temp/llvm_root_dir

cd ~
mkdir ycm_build
cd ycm_build
cmake -G "Unix Makefiles" -DPATH_TO_LLVM_ROOT=~/ycm_temp/llvm_root_dir . ~/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp
sudo cmake --build . --target ycm_core --config Release

cd ~
mkdir regex_build
cd regex_build
cmake -G "Unix Makefiles" . ~/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/cregex
sudo cmake --build . --target _regex --config Release

cp ~/.vim/bundle/YouCompleteMe/third_party/ycmd/examples/.ycm_extra_conf.py ~/


