#!/bin/sh
echo '---------------- remove system vim & install depedents --------------------'
sudo rm ~/.vimrc
sudo rm ~/.viminfo
#sudo rm ~/.vim -rf
sudo apt-get remove vim vim-common vim-tiny 
sudo apt-get install libncurses5-dev libgnome2-dev libgnomeui-dev \
    libgtk2.0-dev libatk1.0-dev libbonoboui2-dev \
    libcairo2-dev libx11-dev libxpm-dev libxt-dev python-dev \
    python3-dev ruby-dev lua5.1 lua5.1-dev libperl-dev git \
    cmake

echo '------------------------- clone vim source --------------------------------'
cd ~/prog
git clone https://github.com/vim/vim.git
cd vim/src
./configure --with-features=huge \
            --enable-multibyte \
            --enable-rubyinterp=yes \
            --enable-pythoninterp=yes \
            --with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu \
            --enable-perlinterp=yes \
            --enable-luainterp=yes \
            --enable-gui=gtk2 --enable-cscope --prefix=/usr
echo ----'-------------------------- nake vim ----------------------------------'
make VIMRUNTIMEDIR=/usr/share/vim/vim80 -j8
echo '---------------------------- install vim ---------------------------------'
sudo make uninstall
sudo make install

#sudo update-alternatives --install /usr/bin/editor editor /usr/bin/vim 1
#sudo update-alternatives --set editor /usr/bin/vim
#sudo update-alternatives --install /usr/bin/vi vi /usr/bin/vim 1
#sudo update-alternatives --set vi /usr/bin/vim

echo '--------------------------- install Vundle -------------------------------'
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
wget https://raw.githubusercontent.com/houxd/vim/master/.vimrc -O ~/.vimrc

echo '-------------------------- install uncrustify ----------------------------'
rm /tmp/uncrustify -rf
git clone https://github.com/uncrustify/uncrustify /tmp/uncrustify
cd /tmp/uncrustify/
cmake ..
cmake --build .
sudo make install

echo '-------------------------- vim install plugin ----------------------------'
sudo vim -c ':PluginInstall'

#vim<<：PluginInstall
echo '------------------------ install YouCompleteMe ---------------------------'
cd ~/.vim/bundle/YouCompleteMe
git submodule update --init --recursive
./install.py --clang-completer
